export default {
  SIGN_UP_ERROR: "خطا در برقراری ارتباط با سرور",
  WRONG_VERIFICATION_CODE: "کد وارد شده صحیح نمیباشد.",
  RECORD: "رکورد",
  POINT_IN_RECORD: "امتیاز در رکورد فعلی",
  CURRENT_POINT: "امتیاز فعلی",
  RANK: "رتبه",
  START_THE_GAME: "شروع بازی",
  ROLL_THE_DICE: "انداختن تاس",
  CHOOSE_THREE_DIMENTIONS: "سه وجه را انتخاب کنید",
  LOGIN: "ورود",
  REGISTER: "ثبت نام",
  PHONE_NUMBER: "شماره تلفن",
  NAME: "اسم",
  EMPTY_FIELDS_ERROR: "هیچ یک از فیلد ها نمی تواند خالی باشد",
  EMPTY_FIELD_ERROR: "این فیلد نمی تواند خالی بماند",
  INVALID_PHONE_NUMEBERـERROR: "شماره وارد شده معتبر نمی باشد ",
  VERIFICATION: "اعتبارسنجی",
  CODE: "کد اعتبارسنجی",
  SCORE: "امتیاز : ",
  NUMBER_OF_CORRECT_GUESSES: "تعداد حدس های درست: ",
  WILL_YOU_CONTINUE: "آیا ادامه می دهید؟",
  YES: "بله",
  FINISHE_THE_GAME: "اتمام بازی",
  YOUR_POINTS: "امتیازات",
  TOTAL_POINT: "امتیاز کل: ",
  REFRESH: "رفرش امتیازات",
  SCORES: "امتیازات",
  INCREASE_POINT: "افزایش امتیاز با تماشای تبلیغ",
  LOGIN_EN: "Login",
  SIGN_UP_EN: "Sign up",
  COMPLETE_RIGISTRATION: "تکمیل ثبت نام",
  COMPLETE: "تکمیل",
  SAVE: "ذخیره",
  AD_IS_NOT_AVAILABLE: "در حال حاضر تبلیغی در دسترس نیست",
  TRY_AGAIN: "تلاش مجدد",
  YOU_LOST: "شما باختید",
  SHOW_SCORES: "نمایش امتیازیات",
  PROFILE: "پروفایل",
};
